version: '2'
services:
  server:
    image: mjollnir
    volumes:
      - ~/Git/mjollnir:/root/Git/mjollnir
#    command: while true; do sleep 1000; done
#    command: /root/.julia/v0.4/Escher/examples/escher --serve
#    working_dir: /root/.julia/v0.4/Escher/examples


  docker:
    image: docker
    links:
      - server
    volumes:
      - ~/Git/mjollnir:/root/Git/mjollnir
    command: nc -lvvz
